### ISSUE TITLE
Callback get country code

### ISSUE THREAD

**Issue by Dave181295** [MojtabaHs/iPhoneNumberField#62]
The flag feature is nice, but what's the point if we don't know the country code ?
Please add a Callback so when user chooses a flag and adds the a phone number, we get the country code for formatting the number later,users don't want to provide the country code

**Comment by MojtabaHs** [comment]
The code detection is not the responsibility of the UI component, and it's not how SwiftUI works. So you need to get the code from the logic core module instead:

```
import PhoneNumberKit

print(PhoneNumberKit().countryCode(for: "IR"))
```

Also, I've put a workaround that you can directly call the core functions within the SwiftUI View. So you can get the country code of the number if the number is completely provided:

```
iPhoneNumberField(
    "Title",
    text: $text,
    isEditing: $isEditing,
    formatted: true
) {
    print($0.phoneNumber?.countryCode)
}
```

**Comment by Dave181295** [comment]
Hey, after trying this workaround I noticed the country code will be nil if the provided number doesn't match the region 

the goal is to apply the country code automatically based on the phone number provided

**Comment by colinmasters** [comment]
I think the users request is valid here: The goal of formatting and validation is so that you can know that the number is valid, but the string returned in the binding is a formatted one, there should probably be a second binding which contains the full number with country code so that we can actually get that value and use it elsewhere in code. Otherwise, this just makes it look pretty.
